# Generated by Django 5.1 on 2024-09-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_is_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='owner',
            field=models.CharField(choices=[('K', 'K'), ('A', 'A')], default='K', max_length=50),
            preserve_default=False,
        ),
    ]
