# Generated by Django 5.1 on 2024-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_rename_date_receipt_save_date_remove_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('for_study', 'Na studia'), ('work_income', 'Przychód praca'), ('family_income', 'Przychód rodzina'), ('investments_income', 'Inwestycje, Lokaty & Oszczędności'), ('money_back', 'Zwrot'), ('other', 'Inne')], max_length=50),
        ),
    ]
