# Generated by Django 5.1 on 2024-09-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_income_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='expenses',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
