# Generated by Django 5.1 on 2024-09-04 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_remove_expenses_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
