# Generated by Django 5.1 on 2024-09-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_transaction_remove_expenses_receipt_delete_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payer',
            field=models.CharField(choices=[('kamil', 'Kamil'), ('ania', 'Ania'), ('common', 'Wspólne')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('fuel', 'Paliwo'), ('car_expenses', 'Wydatki na samochód'), ('fastfood', 'Fast Food'), ('alcohol', 'Alkohol'), ('food_drinks', 'Picie & jedzenie'), ('chemistry', 'Chemia'), ('clothes', 'Ubrania'), ('electronics_games', 'Elektornika & gry'), ('tickets_entrance', 'Bilety & wejściówki'), ('other_shopping', 'Inne zakupy'), ('flat_bills', 'Rachunki za mieszkanie'), ('monthly_subscriptions', 'Miesięczne subskrypcje'), ('other_cyclical_expenses', 'Inne cykliczne wydatki'), ('investments_savings', 'Inwestycje & oszczędności'), ('other', 'Inne'), ('for_study', 'Na studia'), ('work_income', 'Przychód z pracy'), ('family_income', 'Przychód od rodziny'), ('investments_income', 'Przychód z inwestycji'), ('money_back', 'Zwrot pieniędzy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.CharField(choices=[('kamil', 'Kamil'), ('ania', 'Ania'), ('common', 'Wspólne')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Wydatki'), ('income', 'Przychody')], max_length=10),
        ),
    ]
