# Generated by Django 5.1 on 2024-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='shop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
