# Generated by Django 5.1 on 2024-08-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('paliwo', 'Paliwo'), ('wydatki_samochód', 'Wydatki Samochód'), ('fastfood', 'Fastfood'), ('alkohol', 'Alkohol'), ('picie_jedzenie', 'Picie & Jedzenie'), ('chemia', 'Chemia'), ('ubrania', 'Ubrania'), ('elektronika_gry', 'Elektronika & Gry'), ('bilety_wejsciowki', 'Bilety & Wejściówki'), ('inne_zakupy', 'Inne Zakupy'), ('opis_zakupow', 'Opis Zakupów'), ('mieszkanie', 'Mieszkanie'), ('miesieczne_subskrypcje', 'Miesięczne Subskrypcje'), ('inne_cykliczne_wydatki', 'Inne Cykliczne Wydatki'), ('inwestycje_lokaty_oszczednosci', 'Inwestycje, Lokaty & Oszczędności'), ('inne', 'Inne'), ('opis_innych', 'Opis Innych')], max_length=50)),
                ('payer', models.CharField(choices=[('K', 'K'), ('A', 'A')], max_length=1)),
                ('owner', models.CharField(choices=[('K', 'K'), ('A', 'A'), ('Wspólne', 'Wspólne')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('na_studia', 'Na studia'), ('saldo_z_poprzedniego_miesiaca', 'Saldo z poprzedniego miesiąca'), ('przychod', 'Przychód'), ('przychod_rodzina', 'Przychód rodzina'), ('inwestycje_lokaty_oszczednosci', 'Inwestycje, Lokaty & Oszczędności'), ('zwrot', 'Zwrot'), ('inne', 'Inne'), ('opis', 'Opis')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
