# Generated by Django 5.1 on 2024-09-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
