# Generated by Django 5.1 on 2024-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_summary_income_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='amount',
        ),
        migrations.AddField(
            model_name='summary',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='owner',
            field=models.CharField(choices=[('K', 'K'), ('A', 'A'), ('Wspólne', 'Wspólne')], default='K', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
