# Generated by Django 5.1 on 2024-09-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_summary_amount_summary_balance_summary_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('paliwo', 'Paliwo'), ('wydatki_samochód', 'Wydatki Samochód'), ('fastfood', 'Fastfood'), ('alkohol', 'Alkohol'), ('picie_jedzenie', 'Picie & Jedzenie'), ('chemia', 'Chemia'), ('ubrania', 'Ubrania'), ('elektronika_gry', 'Elektronika & Gry'), ('bilety_wejsciowki', 'Bilety & Wejściówki'), ('inne_zakupy', 'Inne Zakupy'), ('opis_zakupow', 'Opis Zakupów'), ('mieszkanie', 'Mieszkanie'), ('miesieczne_subskrypcje', 'Miesięczne Subskrypcje'), ('inne_cykliczne_wydatki', 'Inne Cykliczne Wydatki'), ('inwestycje_lokaty_oszczednosci', 'Inwestycje, Lokaty & Oszczędności'), ('inne', 'Inne'), ('opis_innych', 'Opis Innych')], max_length=50)),
                ('payer', models.CharField(choices=[('K', 'K'), ('A', 'A')], max_length=1)),
                ('owner', models.CharField(choices=[('K', 'K'), ('A', 'A'), ('Wspólne', 'Wspólne')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_shared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AddField(
            model_name='expenses',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.receipt'),
        ),
    ]
