# Generated by Django 5.1 on 2024-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expenses_category_alter_expenses_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='custom_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
