# Generated by Django 5.1 on 2024-09-01 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_receipt_custom_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='date',
            new_name='save_date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='is_shared',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='custom_date',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
