# Generated by Django 5.1 on 2024-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_rename_amount_expenses_price_expenses_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='price',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='amount',
            new_name='value',
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='owner',
            field=models.CharField(choices=[('kamil', 'Kamil'), ('ania', 'Ania'), ('common', 'Wspólne')], max_length=50),
        ),
    ]
