# Generated by Django 5.1 on 2024-09-03 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_delete_summary_rename_name_expenses_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='save_date',
        ),
        migrations.AddField(
            model_name='expenses',
            name='save_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
