# Generated by Django 5.1 on 2024-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_rename_date_income_save_date_expenses_save_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='save_date',
        ),
        migrations.AddField(
            model_name='receipt',
            name='shop',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
