# Generated by Django 5.1 on 2024-09-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_expenses_payment_date_expenses_save_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='payment_date',
        ),
    ]
