# Generated by Django 5.1 on 2024-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_expenses_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('save_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('car_expenses', 'Car Expenses'), ('fastfood', 'Fast Food'), ('alcohol', 'Alcohol'), ('food_drinks', 'Food & Drinks'), ('chemistry', 'Chemistry'), ('clothes', 'Clothes'), ('electronics_games', 'Electronics & Games'), ('tickets_entrance', 'Tickets & Entrance'), ('other_shopping', 'Other Shopping'), ('flat_bills', 'Flat Bills'), ('monthly_subscriptions', 'Monthly Subscriptions'), ('other_cyclical_expenses', 'Other Cyclical Expenses'), ('investments_savings', 'Investments & Savings'), ('other', 'Other'), ('for_study', 'For Study'), ('work_income', 'Work Income'), ('family_income', 'Family Income'), ('investments_income', 'Investments Income'), ('money_back', 'Money Back')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(choices=[('kamil', 'Kamil'), ('ania', 'Ania'), ('common', 'Common')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='total_value',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer',
            field=models.CharField(choices=[('kamil', 'Kamil'), ('ania', 'Ania'), ('common', 'Common')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='transactions',
            field=models.ManyToManyField(related_name='receipts', to='expenses.transaction'),
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
