# Generated by Django 5.1 on 2024-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(auto_created=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
