# Generated by Django 5.1 on 2024-09-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_remove_transaction_owner_transaction_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owners',
            field=models.ManyToManyField(related_name='transactions', to='expenses.user'),
        ),
    ]
