# Generated by Django 5.1 on 2024-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_remove_groups_created_at_remove_groups_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payer',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer',
            field=models.ManyToManyField(related_name='receipts', to='expenses.user'),
        ),
    ]
