# Generated by Django 5.1 on 2024-09-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_remove_receipt_payer_receipt_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='users_array',
            field=models.ManyToManyField(related_name='groups', to='expenses.user'),
        ),
    ]
