# Generated by Django 5.1 on 2024-09-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_alter_groups_users_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='payer',
            new_name='payers',
        ),
    ]
