# Generated by Django 5.1 on 2024-09-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0031_rename_payer_receipt_payers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='payers',
            new_name='payer',
        ),
    ]
