# Generated by Django 5.1 on 2024-09-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0033_remove_receipt_payer_receipt_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='users_array',
        ),
        migrations.AddField(
            model_name='groups',
            name='users_array',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='expenses.user'),
        ),
    ]
