# Generated by Django 5.1 on 2024-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0034_remove_groups_users_array_groups_users_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='users_array',
        ),
        migrations.AddField(
            model_name='groups',
            name='users_array',
            field=models.ManyToManyField(to='expenses.user'),
        ),
    ]
