# Generated by Django 5.1 on 2024-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_remove_groups_users_array_groups_users_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payer',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payer',
            field=models.ManyToManyField(related_name='receipts', to='expenses.user'),
        ),
    ]
