# Generated by Django 5.1 on 2025-06-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0027_instrument_remove_transaction_investment_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invest',
            name='units',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('stock', 'Akcje'), ('etf', 'ETF'), ('bond', 'Obligacje'), ('crypto', 'Kryptowaluty'), ('commodity', 'Surowce'), ('fund', 'Fundusze'), ('other', 'Inne')], max_length=20),
        ),
    ]
