# Generated by Django 5.1 on 2025-07-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0028_invest_purchase_price_invest_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='actual_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='expected_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
