# Generated by Django 5.1 on 2025-07-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0029_wallet_actual_profit_wallet_expected_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='total_value',
            new_name='total_profit',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='parent_wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='total_invest_income',
        ),
    ]
