# Generated by Django 5.1 on 2025-07-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0030_rename_total_value_wallet_total_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='market',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='actual_profit',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='expected_profit',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='total_profit',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='WalletSnapshot',
        ),
    ]
