# Generated by Django 5.1 on 2025-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0031_remove_instrument_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('symbol',)},
            },
        ),
    ]
