# Generated by Django 5.1 on 2025-07-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0032_instrumentpricecache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('name', 'symbol', 'category')},
        ),
    ]
