# Generated by Django 5.1 on 2025-07-07 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0034_invest_capitalization_invest_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('deposit', 'Lokata'), ('fund', 'Fundusz'), ('stock', 'Akcja'), ('etf', 'ETF'), ('bond', 'Obligacja')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capitalization', models.CharField(blank=True, max_length=20, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('deposit', 'Wpłata'), ('withdrawal', 'Wypłata'), ('profit', 'Kapitalizacja/zysk')], max_length=16)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invest',
            name='instrument',
        ),
        migrations.DeleteModel(
            name='InstrumentPriceCache',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='backend_api.wallet'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend_api.investment'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Invest',
        ),
    ]
