# Generated by Django 5.1 on 2025-07-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0035_investment_investmenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
