# Generated by Django 5.1 on 2025-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0036_investmenttransaction_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
